[tox]
envlist = py311, lint, format, mypy, security
isolated_build = true
min_version = 3.24

[testenv]
skip_install = true
allowlist_externals = poetry, mkdir
setenv =
    PYTHONPATH = {toxinidir}/cicd_practice
commands =
    mkdir -p reports/coverage
    poetry run coverage run -m pytest -v {toxinidir}/cicd_practice/tests
    poetry run coverage report
    poetry run coverage html

[testenv:lint]
skip_install = true
allowlist_externals = poetry
commands =
    poetry run ruff check .

[testenv:format]
skip_install = true
allowlist_externals = poetry
commands =
    poetry run ruff format --check .

[testenv:mypy]
skip_install = true
allowlist_externals = poetry
commands = poetry run mypy {toxinidir}/cicd_practice/app.py

[testenv:security]
skip_install = true
allowlist_externals = osv-scanner
commands = osv-scanner .

[gh-actions]
python =
    3.11: py311
